# Generated by Django 4.2.4 on 2023-08-17 19:54

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_category_selfie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=320)),
                ('approved', models.BooleanField(default=False)),
                ('dni_number', models.CharField(max_length=8)),
                ('dni_front', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_dni_front.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='dni')),
                ('dni_back', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_dni_back.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='dni')),
                ('dni_selfie', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_dni_selfie.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='dni')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('Category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
