# Generated by Django 4.2.4 on 2023-08-17 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_selfie'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gender'),
        ),
    ]
