# Generated by Django 4.2.4 on 2023-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gender_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
