# Generated by Django 4.2.4 on 2023-08-17 02:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selfie',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_selfie.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='selfie'),
        ),
    ]
